### ISSUE TITLE
Define an open source license

### ISSUE THREAD

**Issue by benbroce** [robertsonics/Octaphon#1]
I am an employee of the Brigham Young University MEDIC Lab, and this project looks like just what we need to kickstart a medical device prototype we are developing (which requires a 2- to 8-channel Raspberry Pi audio output).

You state in the Octaphon description that this project is open source, but unfortunately, without a license listed, we cannot use it as such (see [https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository)) Could you please specify which license this project is released under?

If you are also willing to release the associated hardware design and firmware as open source, that would be greatly appreciated, but Octaphon will be a great help regardless.

**Comment by robertsonics** [comment]
Thanks for pointing this out. I'll review the license info and make adjustments to this repo accordingly. Regarding the hardware and firmware, I will likely not release the firmware source since it uses code from my closed-source commercial products. Because I don't plan to proceed with this, I can provide the KiCad files for the board, but you would need to write your own firmware.

While the theory of operation is valid, there are issues with the stability of the current working version. Specifically, if there are errors and subsequent recovery in the alsa audio stream, the channel assignments and ordering can get out of whack after the initial configuration. Further work would be necessary to guard against this happening, but I don't plan to continue.

In the meantime, HiFiBerry has announced their own 8-channel board for the RPi 5. It looks promising and I would suggest you investigate that as a commercially available option.

https://www.hifiberry.com/shop/boards/hifiberry-dac8x/

**Comment by benbroce** [comment]
Thank you for the response. We would very much appreciate the licensing adjustment and the KiCAD files, and appreciate your generosity there. We will also look into the HiFiBerry board, and see what will best meet our needs.

**Comment by robertsonics** [comment]
I'm a little confused... I realized when I went to do this that the source modules already contain a header that states they are covered under the GNU General Public License V3, and while I didn't include the actual license file in the repo, the module headers contain a link to it. Did you not see this? In any event, I added the license file.

The 8-channel Pi Hat KiCad files are here:

https://github.com/robertsonics/TsunamiPi_PCB

**Comment by benbroce** [comment]
I apologize, I definitely missed that. There is at least one file (MyLookAndFeel.h) that did not have the license header, so I either missed the header for the others or I read only that file. Thank you nonetheless for placing the general license file, and for publicizing the PCB files. We appreciate your time.
